### ISSUE TITLE
Single item from /app endpoint not returned in an array

### ISSUE THREAD

**Issue by ricoroodenburg** [aaronparker/evergreen-api#21]
Hi,

When requesting information about an application, you will get a response with properties.
If the endpoint return more then one item, the items are stored in a JSON object, for example:

`[
    {
        "Version": "121.0.2256.2",
        "Platform": "Any",
        "Channel": "Policy",
        "Release": "Enterprise",
        "Architecture": "any",
        "Hash": "EE46FC1C6663E44745BE3637DCFA775B703A224B4F097678CEC6D47E33983625",
        "URI": "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/21b293b0-6f4e-41a9-a3a9-f3f43ae5f91c/MicrosoftEdgePolicyTemplates.cab"
    },
    {
        "Version": "121.0.2256.2",
        "Platform": "Windows",
        "Channel": "Dev",
        "Release": "Consumer",
        "Architecture": "arm64",
        "Hash": "524F56766D53EFB7CCE4AE502200AE65ABA94533D1F37722699DC7822C80A89C",
        "URI": "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3bf5fa9-9146-436c-b5e8-b868d27d457d/MicrosoftEdgeDevEnterpriseARM64.msi"
    },
]`

However, the behavior is different once only one item is returned. See the following example:
`{
    "Version": "8.10.20",
    "URI": "https://cache.agilebits.com/dist/1P/win8/1PasswordSetup-8.10.20.exe"
}`

This is not consistent and should be fixed. 
In PowerShell this can be fixed as follow:

Make use of the following syntax `ConvertTo-Json @($Object)` instead of `$Object | ConvertTo-Json`

**Comment by ricoroodenburg** [comment]
I can't find the source script which will push the app data to Cloudflare KV, otherwise I could change it by myself. See https://github.com/aaronparker/evergreen-api/issues/20

**Comment by aaronparker** [comment]
This will be in the AppTracker repo. I will update this

**Comment by aaronparker** [comment]
Closing this issue, as this has been updated in the aaronparker/apptracker repo.
